/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContentsRouteImport } from './routes/contents'
import { Route as ReadPartIdRouteImport } from './routes/read.$partId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsRoute = ContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPartIdRoute = ReadPartIdRouteImport.update({
  id: '/read/$partId',
  path: '/read/$partId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contents': typeof ContentsRoute
  '/read/$partId': typeof ReadPartIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contents': typeof ContentsRoute
  '/read/$partId': typeof ReadPartIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contents': typeof ContentsRoute
  '/read/$partId': typeof ReadPartIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contents' | '/read/$partId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contents' | '/read/$partId'
  id: '__root__' | '/' | '/about' | '/contents' | '/read/$partId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContentsRoute: typeof ContentsRoute
  ReadPartIdRoute: typeof ReadPartIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents': {
      id: '/contents'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$partId': {
      id: '/read/$partId'
      path: '/read/$partId'
      fullPath: '/read/$partId'
      preLoaderRoute: typeof ReadPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContentsRoute: ContentsRoute,
  ReadPartIdRoute: ReadPartIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
